"""Default argument values; used as-is for the `test` mode"""

import os
from typing import Dict, Union

from .shared import get_upper_dir

TOGA_DIR: str = get_upper_dir(__file__, 4)
TEST_INPUT: str = os.path.join(TOGA_DIR, "test_input")
MODELS: str = os.path.join(TOGA_DIR, "models")
SUPPLY: str = os.path.join(TOGA_DIR, "supply")
PROFILES: str = os.path.join(SUPPLY, "CESAR2.0", "profiles")
HUMAN_PROFILES: str = os.path.join(PROFILES, "human")
BIN: str = os.path.join(TOGA_DIR, "bin")

DEFAULT_ARGS: Dict[str, Union[str, int, float, bool, None]] = {
    "ref_2bit": os.path.join(TEST_INPUT, "hg38", "hg38.2bit"),
    "query_2bit": os.path.join(TEST_INPUT, "mm10", "mm10.2bit"),
    "chain_file": os.path.join(
        TEST_INPUT, "hg38", "lastz", "vs_mm10", "axtChain", "hg38.mm10.allfilled.chain"
    ),
    "ref_annotation": os.path.join(
        TEST_INPUT, "hg38", "TOGA2", "currentAnnotation", "hg38.toga.transcripts.bed"
    ),
    "isoform_file": os.path.join(
        TEST_INPUT, "hg38", "TOGA2", "currentAnnotation", "hg38.toga.isoforms.tsv"
    ),
    "no_isoform_file": False,
    "u12_file": None,
    "no_u12_file": os.path.join(
        TEST_INPUT, "hg38", "TOGA2", "currentAnnotation", "hg38.toga.U12introns.tsv"
    ),
    "spliceai_dir": None,
    "no_spliceai": False,
    "input_directory": None,
    "ref_name": None,
    "query_name": None,
    "resume_from": "all",
    "halt_at": "all",
    "selected_feature_batches": None,
    "selected_preprocessing_batches": None,
    "selected_alignment_batches": None,
    "no_utr_annotation": False,
    "min_chain_score": 5000,
    "min_orthologous_chain_score": 15000,
    "feature_jobs": 100,
    "orthology_threshold": 0.5,
    "single_exon_model": os.path.join(MODELS, "se_model.dat"),
    "multi_exon_model": os.path.join(MODELS, "me_model.dat"),
    "use_long_distance_model": False,
    "long_distance_model": os.path.join(MODELS, "ld_model.dat"),
    "disable_fragment_assembly": False,
    "orthologs_only": False,
    "one2ones_only": False,
    "paralogs_over_spanning": False,
    "enable_spanning_chains": False,
    "annotate_processed_pseudogenes": False,
    "preprocessing_jobs": 300,
    "max_chains_per_transcript": 100,
    "cesar_memory_limit": 15.0,
    "max_search_space_size": 1000000,
    "extrapolation_modifier": 1.2,
    "minimal_covered_fraction": 0.0,
    "exon_locus_flank": 100,
    "assembly_gap_size": 10,
    "cesar_profile_dir": HUMAN_PROFILES,
    "cesar_canon_u2_acceptor": None,#os.path.join(HUMAN_PROFILES, "canon_U2_acceptor.tsv"),
    "cesar_canon_u2_donor": None,#os.path.join(HUMAN_PROFILES, "canon_U2_donor.tsv"),
    "cesar_non_canon_u2_acceptor": None,#os.path.join(HUMAN_PROFILES, "nonCanon_U2_acceptor.tsv"),
    "cesar_non_canon_u2_donor": None,#os.path.join(HUMAN_PROFILES, "nonCanon_U2_donor.tsv"),
    "cesar_canon_u12_acceptor": None,#os.path.join(HUMAN_PROFILES, "canon_U12_acceptor.tsv"),
    "cesar_canon_u12_donor": None,#os.path.join(HUMAN_PROFILES, "canon_U12_donor.tsv"),
    "cesar_non_canon_u12_acceptor": None,#os.path.join(HUMAN_PROFILES, "equiprobable_acceptor.tsv"),
    "cesar_non_canon_u12_donor": None,#os.path.join(HUMAN_PROFILES, "non_canon_U12_donor.tsv"),
    "cesar_first_acceptor": os.path.join(PROFILES, "firstCodon_profile.tsv"),
    "cesar_last_donor": os.path.join(PROFILES, "lastCodon_profile.tsv"),
    "joint_splice_site_treatment": False,
    "bigwig2wig_binary": None,
    "min_splice_prob": 0.02,
    "splice_prob_margin": 0.02,
    "intron_gain_check": False,
    "intron_gain_threshold": 0.5,
    "min_intron_prob_trusted": 0.1,
    "min_intron_prob_supported": 0.2,
    "min_intron_prob_unsupported": 0.8,
    "max_intron_number": 4,
    "cesar_binary": None,
    "memory_bins": "3,5,7,10,15",
    "job_nums_per_bin": "500,20,20,10,5",
    "allow_heavy_jobs": False,
    "matrix": os.path.join(SUPPLY, "BLOSUM62.txt"),
    "mask_n_terminal_mutations": False,
    "disable_missing_stop_search": False,
    "account_for_alternative_frame": False,
    "spliceai_correction_mode": 0,
    "accepted_loss_symbols": "FI,I,PI,UL",
    "skip_gene_trees": False,
    "use_raxml": False,
    "max_clique_size": 50,
    "orthology_jobs": 100,
    "prank_binary": None,
    "tree_binary": os.path.join(BIN, "iqtree2"),
    "tree_cpus": 1,
    "utr_abs_threshold": 3000,
    "utr_rel_threshold": 2.5,
    "no_utr_boundary_extrapolation": False,
    "no_adjacent_utr_extra": False,
    "fixed_adjacent_utr_extra": False,
    "link_file": None,
    "parallel_strategy": "local",
    "nextflow_exec_script": None,
    "max_number_of_retries": 3,
    "nextflow_config_dir": None,
    "max_parallel_time": 24,
    "keep_nextflow_log": False,
    "cluster_queue_name": "batch",
    "legacy_chain_feature_extraction": False,
    "toga1_compatible": False,
    "toga1_plus_corrected_cesar": False,
    "output": None,
    "project_name": "TOGA2",
    "project_arg_format": "yaml",
    "keep_temporary_files": False,
    "verbose": True,
    "debug": False,
    "email": None,
    "mailx_binary": None,
    "fatotwobit_binary": None,
    "twobittofa_binary": None,
    "bedtobigbed_binary": None,
    "ixixx_binary": None,
    "ucsc_prefix": "HLTOGAAnnot",
    "ignore_crashed_parallel_batches": False,
    "container_image": None,
    "container_executor": "apptainer",
    "bindings": None
}
